/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteRouteImport } from './routes/staff/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StaffXreadingRouteImport } from './routes/staff/xreading'
import { Route as StaffPosRouteImport } from './routes/staff/pos'
import { Route as StaffOrdersRouteImport } from './routes/staff/orders'
import { Route as StaffInventoryRouteImport } from './routes/staff/inventory'
import { Route as StaffExpensesRouteImport } from './routes/staff/expenses'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminMenuRouteImport } from './routes/admin/menu'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminCashLogsRouteImport } from './routes/admin/cash-logs'
import { Route as AdminAccountsRouteImport } from './routes/admin/accounts'
import { Route as ApiCronUpdateYesterdayStockRouteImport } from './routes/api/cron/update-yesterday-stock'
import { Route as ApiCronPurgeOldDataRouteImport } from './routes/api/cron/purge-old-data'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const StaffRouteRoute = StaffRouteRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const StaffXreadingRoute = StaffXreadingRouteImport.update({
  id: '/xreading',
  path: '/xreading',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffPosRoute = StaffPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffOrdersRoute = StaffOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffInventoryRoute = StaffInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffExpensesRoute = StaffExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => StaffRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCashLogsRoute = AdminCashLogsRouteImport.update({
  id: '/cash-logs',
  path: '/cash-logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiCronUpdateYesterdayStockRoute =
  ApiCronUpdateYesterdayStockRouteImport.update({
    id: '/api/cron/update-yesterday-stock',
    path: '/api/cron/update-yesterday-stock',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronPurgeOldDataRoute = ApiCronPurgeOldDataRouteImport.update({
  id: '/api/cron/purge-old-data',
  path: '/api/cron/purge-old-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/cash-logs': typeof AdminCashLogsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/staff/expenses': typeof StaffExpensesRoute
  '/staff/inventory': typeof StaffInventoryRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/pos': typeof StaffPosRoute
  '/staff/xreading': typeof StaffXreadingRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/purge-old-data': typeof ApiCronPurgeOldDataRoute
  '/api/cron/update-yesterday-stock': typeof ApiCronUpdateYesterdayStockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/cash-logs': typeof AdminCashLogsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/staff/expenses': typeof StaffExpensesRoute
  '/staff/inventory': typeof StaffInventoryRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/pos': typeof StaffPosRoute
  '/staff/xreading': typeof StaffXreadingRoute
  '/admin': typeof AdminIndexRoute
  '/staff': typeof StaffIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/purge-old-data': typeof ApiCronPurgeOldDataRoute
  '/api/cron/update-yesterday-stock': typeof ApiCronUpdateYesterdayStockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/cash-logs': typeof AdminCashLogsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/staff/expenses': typeof StaffExpensesRoute
  '/staff/inventory': typeof StaffInventoryRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/pos': typeof StaffPosRoute
  '/staff/xreading': typeof StaffXreadingRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/purge-old-data': typeof ApiCronPurgeOldDataRoute
  '/api/cron/update-yesterday-stock': typeof ApiCronUpdateYesterdayStockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/staff'
    | '/admin/accounts'
    | '/admin/cash-logs'
    | '/admin/inventory'
    | '/admin/menu'
    | '/admin/orders'
    | '/staff/expenses'
    | '/staff/inventory'
    | '/staff/orders'
    | '/staff/pos'
    | '/staff/xreading'
    | '/admin/'
    | '/staff/'
    | '/api/auth/$'
    | '/api/cron/purge-old-data'
    | '/api/cron/update-yesterday-stock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/accounts'
    | '/admin/cash-logs'
    | '/admin/inventory'
    | '/admin/menu'
    | '/admin/orders'
    | '/staff/expenses'
    | '/staff/inventory'
    | '/staff/orders'
    | '/staff/pos'
    | '/staff/xreading'
    | '/admin'
    | '/staff'
    | '/api/auth/$'
    | '/api/cron/purge-old-data'
    | '/api/cron/update-yesterday-stock'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/staff'
    | '/admin/accounts'
    | '/admin/cash-logs'
    | '/admin/inventory'
    | '/admin/menu'
    | '/admin/orders'
    | '/staff/expenses'
    | '/staff/inventory'
    | '/staff/orders'
    | '/staff/pos'
    | '/staff/xreading'
    | '/admin/'
    | '/staff/'
    | '/api/auth/$'
    | '/api/cron/purge-old-data'
    | '/api/cron/update-yesterday-stock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  StaffRouteRoute: typeof StaffRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronPurgeOldDataRoute: typeof ApiCronPurgeOldDataRoute
  ApiCronUpdateYesterdayStockRoute: typeof ApiCronUpdateYesterdayStockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/staff/xreading': {
      id: '/staff/xreading'
      path: '/xreading'
      fullPath: '/staff/xreading'
      preLoaderRoute: typeof StaffXreadingRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/pos': {
      id: '/staff/pos'
      path: '/pos'
      fullPath: '/staff/pos'
      preLoaderRoute: typeof StaffPosRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/orders': {
      id: '/staff/orders'
      path: '/orders'
      fullPath: '/staff/orders'
      preLoaderRoute: typeof StaffOrdersRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/inventory': {
      id: '/staff/inventory'
      path: '/inventory'
      fullPath: '/staff/inventory'
      preLoaderRoute: typeof StaffInventoryRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/expenses': {
      id: '/staff/expenses'
      path: '/expenses'
      fullPath: '/staff/expenses'
      preLoaderRoute: typeof StaffExpensesRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cash-logs': {
      id: '/admin/cash-logs'
      path: '/cash-logs'
      fullPath: '/admin/cash-logs'
      preLoaderRoute: typeof AdminCashLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/cron/update-yesterday-stock': {
      id: '/api/cron/update-yesterday-stock'
      path: '/api/cron/update-yesterday-stock'
      fullPath: '/api/cron/update-yesterday-stock'
      preLoaderRoute: typeof ApiCronUpdateYesterdayStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/purge-old-data': {
      id: '/api/cron/purge-old-data'
      path: '/api/cron/purge-old-data'
      fullPath: '/api/cron/purge-old-data'
      preLoaderRoute: typeof ApiCronPurgeOldDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminCashLogsRoute: typeof AdminCashLogsRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminCashLogsRoute: AdminCashLogsRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface StaffRouteRouteChildren {
  StaffExpensesRoute: typeof StaffExpensesRoute
  StaffInventoryRoute: typeof StaffInventoryRoute
  StaffOrdersRoute: typeof StaffOrdersRoute
  StaffPosRoute: typeof StaffPosRoute
  StaffXreadingRoute: typeof StaffXreadingRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteRouteChildren: StaffRouteRouteChildren = {
  StaffExpensesRoute: StaffExpensesRoute,
  StaffInventoryRoute: StaffInventoryRoute,
  StaffOrdersRoute: StaffOrdersRoute,
  StaffPosRoute: StaffPosRoute,
  StaffXreadingRoute: StaffXreadingRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteRouteWithChildren = StaffRouteRoute._addFileChildren(
  StaffRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  StaffRouteRoute: StaffRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronPurgeOldDataRoute: ApiCronPurgeOldDataRoute,
  ApiCronUpdateYesterdayStockRoute: ApiCronUpdateYesterdayStockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
